### PR TITLE
respect existing OP_SESSION env var

### PR DESCRIPTION
**Pull request by xdays**

### CODE REVIEW

**Review by dtpryce — CHANGES_REQUESTED** [review]
This will only work if account is set already ... What if this is the first usage? 

I think this could be added if there was also a check that account has been set / isn't None.

**Comment by dtpryce** [comment]
@xdays we are about to update our release pipeline and with this a new version including your change, is that ok for you?

**Comment by dtpryce** [comment]
If you want to try early it should be on this branch https://github.com/wandera/1password-client/tree/pre-installed-op and you can install locally using `pip install -e . ` or `python setup.py install` ... otherwise wait for the new version and test there

**Comment by xdays** [comment]
> This will only work if account is set already ... What if this is the first usage?
> 
> I think this could be added if there was also a check that account has been set / isn't None.

If the account is not set, there should be no env var `"OP_SESSION_{}".format(account)`

**Comment by dtpryce** [comment]
Version 0.6.0 released and should include you fix: `pip install 1password==0.6.0`

**Pull request closed without merging**
